### ISSUE TITLE
Flutter有关的bug写在这里

### ISSUE THREAD

**Issue by AweiLoveAndroid** [AweiLoveAndroid/awesome-bug#7]
这里是关于Flutter开发中遇到的一些bug  写在这里。感谢大家多多支持。

**Comment by zhanzengyu** [comment]
Q:flutter 在pubspec.yaml添加依赖报错.
```
Error on line 25, column 5 of pubspec.yaml: A dependency may only have one source.
sdk: flutter
^^^^^^^^^^^^^

pub get failed (65)
```
A:这个是对齐问题
```
dev_dependencies:
  flutter_test:
    sdk: flutter

    english_words: ^3.1.0
```
这样会报错。库要跟flutter_test对齐。所以缩进一下 english_words 行就可以了。
```
dev_dependencies:
  flutter_test:
    sdk: flutter

  english_words: ^3.1.0
```
